name: Continuous Deployment - Iris API

on:
  workflow_dispatch:
  pull_request:
    branches: main

permissions:
  contents: read
  pull-requests: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Authenticate with GCP
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        install_components: "gke-gcloud-auth-plugin"

    - name: Authenticate to GKE cluster
      uses: google-github-actions/get-gke-credentials@v2
      with:
        cluster_name:  ${{ secrets.GKE_CLUSTER }}
        location: ${{ secrets.GKE_ZONE }}

    - name: Configure Docker for Artifact Registry
      run: |
        gcloud auth configure-docker us-central1-docker.pkg.dev

    - name: Build and Push Docker Image to Artifact Registry
      run: |
        docker build -t us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-repo/iris-api:latest .
        docker push us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/my-repo/iris-api:latest
        
    # - name: Install gke-gcloud-auth-plugin (gcloud way)
    #   run: |
    #     gcloud components install gke-gcloud-auth-plugin --quiet
        
    # - name: Get GKE Credentials
    #   run: |
    #     gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER }} --zone ${{ secrets.GKE_ZONE }}

    - name: Deploy to GKE
      run: |
        kubectl apply -f k8/deployment.yaml
        kubectl apply -f k8/service.yaml

    - name: Setup CML
      uses: iterative/setup-cml@v2

    - name: Comment results with CML
      env:
        REPO_TOKEN: ${{ secrets.PAT }}
      run: |
        echo "Iris API deployed to Kubernetes using Artifact Registry." > report.md
        kubectl get pods >> report.md
        cml comment update --publish report.md
        
